---
title: "Straightness_Index"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries
```{r}
packages <- c('trajr','sp','lubridate')

install_load <- function(packages){
     for (p in packages) {
          if (p %in% rownames(installed.packages())) {
               library(p, character.only=TRUE)
          } else {
               install.packages(p)
               library(p,character.only = TRUE)
          }
     }
}

install_load(packages)
```

# ATS Pre Fire
```{r}
deer <- read.csv(here::here("Publication_Data","Collars","ATS","ATSPreFire.csv"))
deer <- deer[c(complete.cases(deer)),]
xy <- deer[,c("Longitude","Latitude")]  ## get lat/long from data frame
coordinates(xy) <- c("Longitude", "Latitude")
proj4string(xy) <- CRS("+proj=longlat +datum=WGS84")
res <- spTransform(xy, CRS("+proj=utm +zone=10 ellps=WGS84"))
res2 <- as.data.frame(res)
colnames(res2) <- c("Longitude.utm","Latitude.utm")
deer <- bind_cols(deer, res2)

H3 <- deer[c(deer$AnimalID=="H3"),]
P4 <- deer[c(deer$AnimalID=="P4"),]

#H3
coords <- data.frame(x=H3$Longitude.utm, y = H3$Latitude.utm, times=H3$Time, id=H3$AnimalID)
trj <- TrajFromCoords(coords)
plot(trj)


TrajStraightness(trj) 

#P4
coords <- data.frame(x=P4$Longitude.utm, y = P4$Latitude.utm, times=P4$Time, id=P4$AnimalID)
trj <- TrajFromCoords(coords)
plot(trj)


TrajStraightness(trj)
```

# ATS Post Fire
```{r}
deer <- read.csv(here::here("Publication_Data","Collars","ATS","ATSPostFire.csv"))
deer <- deer[c(complete.cases(deer)),]
xy <- deer[,c("Longitude","Latitude")]  ## get lat/long from data frame
coordinates(xy) <- c("Longitude", "Latitude")
proj4string(xy) <- CRS("+proj=longlat +datum=WGS84")
res <- spTransform(xy, CRS("+proj=utm +zone=10 ellps=WGS84"))
res2 <- as.data.frame(res)
colnames(res2) <- c("Longitude.utm","Latitude.utm")
deer <- bind_cols(deer, res2)

H3 <- deer[c(deer$AnimalID=="H3"),]
P4 <- deer[c(deer$AnimalID=="P4"),]

#H3
coords <- data.frame(x=H3$Longitude.utm, y = H3$Latitude.utm, times=H3$Time, id=H3$AnimalID)
trj <- TrajFromCoords(coords)
plot(trj)


TrajStraightness(trj)

#P4
coords <- data.frame(x=P4$Longitude.utm, y = P4$Latitude.utm, times=P4$Time, id=P4$AnimalID)
trj <- TrajFromCoords(coords)
plot(trj)


TrajStraightness(trj)
```

# Vectronic Pre Fire
```{r}
deer <- read.csv(here::here("Publication_Data","Collars","Vectronic","VectronicPreFire.csv"))
deer <- deer[c(complete.cases(deer)),]
colnames(deer)[15]<-'Longitude'
colnames(deer)[14]<-'Latitude'
xy <- deer[,c("Longitude","Latitude")]  ## get lat/long from data frame
coordinates(xy) <- c("Longitude", "Latitude")
proj4string(xy) <- CRS("+proj=longlat +datum=WGS84")
res <- spTransform(xy, CRS("+proj=utm +zone=10 ellps=WGS84"))
res2 <- as.data.frame(res)
colnames(res2) <- c("Longitude.utm","Latitude.utm")
deer <- bind_cols(deer, res2)


# Animal IDs include: A5b, D3b, H2, H4, H5, I5, J1, J2, J3, J5, K1, K2, Q5
coords <- data.frame(x=deer[deer$AnimalID=="K2",]$Longitude.utm, y = deer[deer$AnimalID=="K2",]$Latitude.utm, times=deer[deer$AnimalID=="K2",]$Time, id=deer[deer$AnimalID=="K2",]$AnimalID)
trj <- TrajFromCoords(coords)
plot(trj)


TrajStraightness(trj)
```

# Vectronic Post Fire
```{r}
deer <- read.csv(here::here("Publication_Data","Collars","Vectronic","VectronicPostFire.csv"))
deer <- deer[c(complete.cases(deer)),]
colnames(deer)[15]<-'Longitude'
colnames(deer)[14]<-'Latitude'
xy <- deer[,c("Longitude","Latitude")]  ## get lat/long from data frame
coordinates(xy) <- c("Longitude", "Latitude")
proj4string(xy) <- CRS("+proj=longlat +datum=WGS84")
res <- spTransform(xy, CRS("+proj=utm +zone=10 ellps=WGS84"))
res2 <- as.data.frame(res)
colnames(res2) <- c("Longitude.utm","Latitude.utm")
deer <- bind_cols(deer, res2)


# Animal IDs include: A5b, D3b, H2, H4, H5, I5, J1, J2, J3, J5, K1, K2, Q5
coords <- data.frame(x=deer[deer$AnimalID=="K2",]$Longitude.utm, y = deer[deer$AnimalID=="K2",]$Latitude.utm, times=deer[deer$AnimalID=="K2",]$Time, id=deer[deer$AnimalID=="K2",]$AnimalID)
trj <- TrajFromCoords(coords)
plot(trj)


TrajStraightness(trj)
```


# Lotek Pre Fire
```{r}
deer <- read.csv(here::here("Publication_Data","Collars","Lotek","LotekPreFire.csv"))
deer <- deer[c(complete.cases(deer)),]
xy <- deer[,c("Longitude","Latitude")]  ## get lat/long from data frame
coordinates(xy) <- c("Longitude", "Latitude")
proj4string(xy) <- CRS("+proj=longlat +datum=WGS84")
res <- spTransform(xy, CRS("+proj=utm +zone=10 ellps=WGS84"))
res2 <- as.data.frame(res)
colnames(res2) <- c("Longitude.utm","Latitude.utm")
deer <- bind_cols(deer, res2)


# Animal IDs include: A4, F2, K4
coords <- data.frame(x=deer[deer$AnimalID=="A4",]$Longitude.utm, y = deer[deer$AnimalID=="A4",]$Latitude.utm, times=deer[deer$AnimalID=="A4",]$TimeStamp, id=deer[deer$AnimalID=="A4",]$AnimalID)
trj <- TrajFromCoords(coords)
plot(trj)


TrajStraightness(trj)
```

# Lotek Post Fire
```{r}
deer <- read.csv(here::here("Publication_Data","Collars","Lotek","LotekPostFire.csv"))
deer <- deer[c(complete.cases(deer)),]
xy <- deer[,c("Longitude","Latitude")]  ## get lat/long from data frame
coordinates(xy) <- c("Longitude", "Latitude")
proj4string(xy) <- CRS("+proj=longlat +datum=WGS84")
res <- spTransform(xy, CRS("+proj=utm +zone=10 ellps=WGS84"))
res2 <- as.data.frame(res)
colnames(res2) <- c("Longitude.utm","Latitude.utm")
deer <- bind_cols(deer, res2)


# Animal IDs include: A4, F2, K4
coords <- data.frame(x=deer[deer$AnimalID=="A4",]$Longitude.utm, y = deer[deer$AnimalID=="A4",]$Latitude.utm, times=deer[deer$AnimalID=="A4",]$TimeStamp, id=deer[deer$AnimalID=="A4",]$AnimalID)
trj <- TrajFromCoords(coords)
plot(trj)


TrajStraightness(trj)
```
