---
title: "Homerange_Isopleth_Generation"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries
```{r}
packages <- c('sp','rgdal','rgeos','maptools','pander')

install_load <- function(packages){
     for (p in packages) {
          if (p %in% rownames(installed.packages())) {
               library(p, character.only=TRUE)
          } else {
               install.packages(p)
               library(p,character.only = TRUE)
          }
     }
}

install_load(packages)

# install tlocoh from source
install.packages("tlocoh", dependencies=TRUE, repos=c("http://R-Forge.R-project.org", "http://cran.cnr.berkeley.edu"), type="source")
```

# Deer Pre Fire
```{r}
toni <- read.csv(here::here("Publication_Data","Collars","deer-gps-prefire.csv"))

# Create Spatial Points Dataframe from lat/longs and project in UTM 10
toni.sp.latlong<-(SpatialPoints(toni[,c("Longitude", "Latitude")], proj4string=CRS("+proj=longlat +ellps=WGS84")))
toni.sp.utm <- spTransform(toni.sp.latlong, CRS("+proj=utm +zone=10 +ellps=WGS84"))

# Create coord matrix and rename to x and y for locoh
toni.mat.utm <- coordinates(toni.sp.utm)
head(toni.mat.utm)
colnames(toni.mat.utm) <- c("x", "y")

# Create time class
toni.localtime <- as.POSIXct(toni$TimeStamp, tz="America/Los_Angeles")

# Create LoCoH isopleths
toni.lxy <- xyt.lxy(xy=toni.mat.utm, dt=toni.localtime, tz= "America/Los_Angeles", id=toni$AnimalID, proj4string=CRS("+proj=utm +zone=10 +ellps=WGS84"), dup.dt.check=FALSE) #create a LoCoH-xy object
toni.lxy <- lxy.nn.add(toni.lxy, s=0, k=25) #identifies nearest neighbors for a LoCoH-xy object
toni.lhs <- lxy.lhs(toni.lxy, k=15, s=0) # Creates a LoCoH-hullset object 
toni.lhs <- lhs.iso.add(toni.lhs) #Adds isopleths toa  LoCoH-hullset object

#Animal IDs to plot in the id argument for this dataset : A4, A5b, D3b, F2, H2, H3, H4, H5, I5, J1, J2, J3, J5, K1, K2, K4, P4, Q5
plot(toni.lhs, iso=T, id = "A5b", k=15, allpts=T, cex.allpts=0.1, col.allpts="gray30", ufipt=F, figs.per.page=1)


##This will export as shapefiles so you can get areas from the isopleth summaries (we'll be taking the 95%)
toni.iso <- isopleths(toni.lhs) #extract just the isopleths from our LoCoH-xy object
A5b.post.iso <- toni.iso[[1]]$area[[5]] #Extracts the 0.95 isopleth homerange area in m^2
#writeOGR(A5b.post.iso, "A5bPost",dsn=here::here(),driver="ESRI Shapefile") #uncomment to export homerange ESRI shapefile

```


# Deer Post Fire
```{r}
toni <- read.csv(here::here("Publication_Data","Collars","deer-gps-postfire.csv"))

# Create Spatial Points Dataframe from lat/longs and project in UTM 10
toni.sp.latlong<-(SpatialPoints(toni[,c("Longitude", "Latitude")], proj4string=CRS("+proj=longlat +ellps=WGS84")))
toni.sp.utm <- spTransform(toni.sp.latlong, CRS("+proj=utm +zone=10 +ellps=WGS84"))

# Create coord matrix and rename to x and y for locoh
toni.mat.utm <- coordinates(toni.sp.utm)
head(toni.mat.utm)
colnames(toni.mat.utm) <- c("x", "y")

# Create time class
toni.localtime <- as.POSIXct(toni$TimeStamp, tz="America/Los_Angeles")

# Create LoCoH isopleths
toni.lxy <- xyt.lxy(xy=toni.mat.utm, dt=toni.localtime, tz= "America/Los_Angeles", id=toni$AnimalID, proj4string=CRS("+proj=utm +zone=10 +ellps=WGS84"), dup.dt.check=FALSE) #create a LoCoH-xy object
toni.lxy <- lxy.nn.add(toni.lxy, s=0, k=25) #identifies nearest neighbors for a LoCoH-xy object
toni.lhs <- lxy.lhs(toni.lxy, k=15, s=0) # Creates a LoCoH-hullset object 
toni.lhs <- lhs.iso.add(toni.lhs) #Adds isopleths toa  LoCoH-hullset object

#Animal IDs to plot in the id argument for this dataset : A4, A5b, D3b, F2, H2, H3, H4, H5, I5, J1, J2, J5, K1, K2, K4, P4, Q5 - Note that this won't be the correct value for Doe J3, see below
plot(toni.lhs, iso=T, id = "A5b", k=15, allpts=T, cex.allpts=0.1, col.allpts="gray30", ufipt=F, figs.per.page=1)


##This will export as shapefiles so you can get areas from the isopleth summaries (we'll be taking the 95%)
toni.iso <- isopleths(toni.lhs) #extract just the isopleths from our LoCoH-xy object
A5b.post.iso <- toni.iso[[1]]$area[[5]] #Extracts the 0.95 isopleth homerange area in m^2
#writeOGR(A5b.post.iso, "A5bPost",dsn=here::here(),driver="ESRI Shapefile") #uncomment to export homerange ESRI shapefile




# Special Case of J3 - Remove points that don't represent home range because J3 fled the fire front
J3 <- toni[toni$AnimalID=="J3",] # Remove J3's return from during fire move over Cow Mountain
J3 <- J3[rownames(J3)<5247,]

# Create Spatial Points Dataframe from lat/longs and project in UTM 10
toni.sp.latlong<-(SpatialPoints(J3[,c("Longitude", "Latitude")], proj4string=CRS("+proj=longlat +ellps=WGS84")))
toni.sp.utm <- spTransform(toni.sp.latlong, CRS("+proj=utm +zone=10 +ellps=WGS84"))

# Create coord matrix and rename to x and y for locoh
toni.mat.utm <- coordinates(toni.sp.utm)
head(toni.mat.utm)

colnames(toni.mat.utm) <- c("x", "y")

# Create time class
toni.localtime <- as.POSIXct(J3$TimeStamp, tz="America/Los_Angeles")

# Create LoCoH isopleths
toni.lxy <- xyt.lxy(xy=toni.mat.utm, dt=toni.localtime, tz= "America/Los_Angeles", id=J3$AnimalID, proj4string=CRS("+proj=utm +zone=10 +ellps=WGS84"), dup.dt.check=FALSE)
lxy.plot.freq(toni.lxy, cp=T)
toni.lxy <- lxy.nn.add(toni.lxy, s=0, k=25)
toni.lhs <- lxy.lhs(toni.lxy, k=15, s=0)#could input krange here
toni.lhs <- lhs.iso.add(toni.lhs)

##This will export as shapefiles so you can get areas from the isopleth summaries (we'll be taking the 95%)
toni.iso <- isopleths(toni.lhs)
A5b.post.iso <- toni.iso[[1]]$area[[5]]
```

