---
title: "Straightness_Index"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
This script calcualtes straightness indices for deer movement

# Load Libraries
```{r}
packages <- c('trajr','sp','lubridate')

install_load <- function(packages){
     for (p in packages) {
          if (p %in% rownames(installed.packages())) {
               library(p, character.only=TRUE)
          } else {
               install.packages(p)
               library(p,character.only = TRUE)
          }
     }
}

install_load(packages)
```


# Pre Fire
```{r}
deer <- read.csv(here::here("Publication_Data","Collars","deer-gps-prefire.csv"))
deer <- deer[c(complete.cases(deer)),]
xy <- deer[,c("Longitude","Latitude")]  ## get lat/long from data frame
coordinates(xy) <- c("Longitude", "Latitude")
proj4string(xy) <- CRS("+proj=longlat +datum=WGS84")
res <- spTransform(xy, CRS("+proj=utm +zone=10 ellps=WGS84"))
res2 <- as.data.frame(res) #convert to dataframe



# Animal IDs include: A5, A5b, D3b, F2, H2, H3, H4, H5, I5, J1, J2, J3, J5, K1, K2, K4, P4, Q5
coords <- data.frame(x=deer[deer$AnimalID=="K2",]$Easting, y = deer[deer$AnimalID=="K2",]$Northing, times=deer[deer$AnimalID=="K2",]$Time, id=deer[deer$AnimalID=="K2",]$AnimalID)
trj <- TrajFromCoords(coords) # create a trajectory object


TrajStraightness(trj) #calculates straightness index of a trajectory



```



# Post Fire
```{r}
deer <- read.csv(here::here("Publication_Data","Collars","deer-gps-postfire.csv"))
deer <- deer[c(complete.cases(deer)),]
xy <- deer[,c("Longitude","Latitude")]  ## get lat/long from data frame
coordinates(xy) <- c("Longitude", "Latitude")
proj4string(xy) <- CRS("+proj=longlat +datum=WGS84")
res <- spTransform(xy, CRS("+proj=utm +zone=10 ellps=WGS84"))
res2 <- as.data.frame(res)



# Animal IDs include: A5, A5b, D3b, F2, H2, H3, H4, H5, I5, J1, J2, J3, J5, K1, K2, K4, P4, Q5
coords <- data.frame(x=deer[deer$AnimalID=="K2",]$Easting, y = deer[deer$AnimalID=="K2",]$Northing, times=deer[deer$AnimalID=="K2",]$Time, id=deer[deer$AnimalID=="K2",]$AnimalID)
trj <- TrajFromCoords(coords)


TrajStraightness(trj)
```

